#!/bin/bash

repo=$1
tgt=$2
deep=false

if [[ "$3" = "submodules" ]]; then
    deep=true
fi

bup_if_not_repo "$tgt"

if [[ ! -d "$tgt" ]]; then
    touch "$CHANGED"
    echo "‘$tgt’ -> ‘$repo’ [cloning]";
    git clone --depth=1 "$repo" "$tgt" || exit $EX_CLONE
    if $deep; then
        pushd "$tgt" > /dev/null
        (git submodule init && git submodule update --remote) || "$MYBIN/fin_message" "Submodule init/update in $tgt"
        popd > /dev/null
    fi
else
    echo -e "${CLR_ALREADY}‘$tgt’ -> ‘$repo’ [already]${CLR_NONE}";
fi
